= Quarkus Jnosql
:toc: auto
include::./includes/attributes.adoc[]

TIP: The Quarkus NoSQL Extension is a powerful integration between Quarkus and Eclipse JNoSQL, allowing seamless interaction with various NoSQL databases in Quarkus applications.

By following the steps outlined in this documentation, Quarkus developers can easily integrate Eclipse JNoSQL into their Quarkus projects, simplify NoSQL database interactions, and build efficient and scalable applications. Eclipse JNoSQL implements two essential Jakarta EE specifications: Jakarta Data and Jakarta NoSQL.

https://github.com/jakartaee/nosql[Jakarta NoSQL] is a Java framework designed to streamline the integration of Java applications with various NoSQL databases. It offers a consistent and easy-to-use API, allowing developers to interact with different NoSQL databases seamlessly.

On the other hand, the https://github.com/jakartaee/data[Jakarta Data specification] provides an API for simplified data access to various database types, including relational and NoSQL databases. Java developers can access these repositories through multiple methods, such as composing custom queries on a Repository interface.

Integrating Eclipse JNoSQL into Quarkus projects ensures adherence to these Jakarta EE standards and leverages the benefits of standardized APIs for enhanced productivity and maintainability.

With the Quarkus NoSQL Extension, Quarkus developers can seamlessly integrate Eclipse JNoSQL into their Quarkus applications. Here's why you should consider using this extension:

TIP: Eclipse JNoSQL combined with Quarkus brings several benefits to developers:

* **Simplified NoSQL Integration:** The Quarkus NoSQL Extension abstracts the complexity of working with different NoSQL databases. Developers can work with a consistent API regardless of the underlying database technology, making it easier to switch between databases or use multiple databases in a single application.
* **Type-Safe Queries:** Eclipse JNoSQL provides a type-safe query API, allowing developers to write database queries using Java code rather than raw query strings. This improves code readability, catches errors at compile-time, and enhances developer productivity.
* **Seamless Quarkus Integration:** Quarkus is known for its fast startup times and efficient resource utilization. By using the Quarkus NoSQL Extension, developers can harness the benefits of Quarkus while working with NoSQL databases, ensuring that their applications remain lightweight and responsive.
* **Database Agnosticism:** The extension supports a wide range of NoSQL databases, including key-value stores, document databases, and column-family stores. This flexibility allows developers to choose the most suitable database for their specific use case without major code changes.
* **Rich Documentation and Ecosystem:** Eclipse JNoSQL has a thriving community and rich documentation, making it easy for developers to find support, tutorials, and examples. By integrating it with Quarkus, developers can tap into the vibrant Quarkus ecosystem as well.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.jnosql:quarkus-jnosql` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Getting Started

By following the steps outlined in this documentation, Quarkus developers can quickly integrate Eclipse JNoSQL into their Quarkus projects, simplify NoSQL database interactions, and build efficient and scalable applications with ease.

1. Add the Quarkus JNoSQL Extension to your project's dependencies. You can find the latest version on Maven Central:

   link:https://img.shields.io/maven-central/v/io.quarkiverse.jnosql/quarkus-jnosql-core?logo=apache-maven&style=flat-square[![Version]]

2. Define your entities using JNoSQL annotations. Here's an example entity class:

[source,java]
----
import jakarta.nosql.Column;
import jakarta.nosql.Entity;
import jakarta.nosql.Id;

@Entity
public class TestEntity {

   @Id
   private String id;

   @Column
   private String testField;
}
----

=== KeyValue

==== Configuration

Configure the JNoSql KeyValue Quarkus extension by specifying the name of the database that will be utilized within the Eclipse JNoSQL framework in your `application.properties`:

[source,properties]
----
jnosql.keyvalue.database=my-database-name
----

==== Usage

Inject the `KeyValueTemplate` into your class and use it to interact with the KeyValue database:

[source,java]
----
import jakarta.inject.Inject;
import org.jnosql.artemis.key.KeyValueTemplate;

@Inject
private KeyValueTemplate template;

public void insert(TestEntity entity) {
    template.insert(entity);
}
----

=== Key-Value Database Specific Configuration

When configuring databases for use with Quarkus and Eclipse JNoSQL, it's important to note that instead of using the traditional Eclipse JNoSQL properties and configuration, Quarkus provides its properties and configuration for seamless integration. Below are sections detailing the configuration specifics for different NoSQL databases within the Quarkus environment.

TIP: Add sections for each specific database configuration, similar to those for ArangoDB, DynamoDB, Hazelcast, and Redis.

==== ArangoDB

Add the ArangoDB dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-keyvalue-arangodb</artifactId>
</dependency>
----

For specific configuration details, please refer to the link:https://github.com/eclipse/jnosql-databases#arangodb[ArangoDB JNoSQL driver].

==== DynamoDB

Add the DynamoDB dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-keyvalue-dynamodb</artifactId>
</dependency>
----

Please refer to the link:https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-dynamodb.html[DynamoDB Quarkiverse extension] for specific configuration details.

==== Hazelcast

Add the Hazelcast dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-keyvalue-hazelcast</artifactId>
</dependency>
----

Please refer to the link:https://github.com/hazelcast/quarkus-hazelcast-client[Quarkus Hazelcast extension] for specific configuration details.

==== Redis

Add the Redis dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-keyvalue-redis</artifactId>
</dependency>
----

For specific configuration details, please refer to the link:https://quarkus.io/guides/redis-reference[Redis Quarkus extension].

=== Document

==== Configuration

Configure the JNoSql Document Quarkus extension by specifying the database's name in your `application.properties`:

[source,properties]
----
jnosql.document.database=my-database-name
----

==== Usage

Inject the `DocumentTemplate` into your class and use it to interact with the Document database:

[source,java]
----
import jakarta.inject.Inject;
import org.jnosql.artemis.document.DocumentTemplate;

@Inject
private DocumentTemplate template;

public void insert(TestDocumentEntity entity) {
    template.insert(entity);
}
----

==== Document Database Specific Configuration

When configuring databases for use with Quarkus and Eclipse JNoSQL, it's important to note that instead of using the traditional Eclipse JNoSQL properties and configuration, Quarkus provides its properties and configuration for seamless integration. Below are sections detailing the configuration specifics for different NoSQL databases within the Quarkus environment.

TIP: Add sections for each specific database configuration, similar to the following sections for ArangoDB, CouchDB, Elasticsearch, MongoDB, and Solr.

==== ArangoDB

Add the ArangoDB dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-document-arangodb</artifactId>
</dependency>
----

For specific configuration details, please refer to the https://github.com/eclipse/jnosql-databases#arangodb[ArangoDB JNoSQL driver].

==== CouchDB

Add the CouchDB dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-document-couchdb</artifactId>
</dependency>
----

For specific configuration details, please refer to the https://github.com/eclipse/jnosql-databases#couchdb[CouchDB JNoSQL driver].

==== Elasticsearch

Add the Elasticsearch dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-document-elasticsearch</artifactId>
</dependency>
----

For specific configuration details, please refer to the https://github.com/eclipse/jnosql-databases?tab=readme-ov-file#elasticsearch[ElasticSearch driver].


include::includes/quarkus-jnosql.adoc[leveloffset=+1, opts=optional]