= Quarkus Jnosql
:toc: auto
include::./includes/attributes.adoc[]

== Introduction

The Quarkus NoSQL Extension facilitates seamless interaction between Quarkus and Eclipse JNoSQL, enabling easy integration with various NoSQL databases in Quarkus applications. By following the steps outlined in this documentation, Quarkus developers can effortlessly incorporate Eclipse JNoSQL into their projects, simplifying NoSQL database interactions and empowering the development of efficient and scalable applications. Eclipse JNoSQL adheres to two essential Jakarta EE specifications: Jakarta Data and Jakarta NoSQL.

https://github.com/jakartaee/nosql[Jakarta NoSQL] is a Java framework designed to streamline the integration of Java applications with various NoSQL databases. It offers a consistent and easy-to-use API, allowing developers to interact with different NoSQL databases seamlessly.

On the other hand, the https://github.com/jakartaee/data[Jakarta Data specification] provides an API for simplified data access to various database types, including relational and NoSQL databases. Java developers can access these repositories through multiple methods, such as composing custom queries on a Repository interface.

Integrating Eclipse JNoSQL into Quarkus projects ensures adherence to these Jakarta EE standards and leverages the benefits of standardized APIs for enhanced productivity and maintainability.

== Why Use Quarkus JNoSQL Extension?

The Quarkus NoSQL Extension offers several advantages for developers:

* Simplified NoSQL Integration: Abstracts the complexity of working with different NoSQL databases, providing a consistent API regardless of the underlying technology. Facilitates easy switching between databases or using multiple databases in a single application.
* Type-Safe Queries: Empowers developers to write database queries using Java code rather than raw query strings, improving code readability and catching errors at compile-time.
* Seamless Quarkus Integration: Utilizes Quarkus' fast startup times and efficient resource utilization while working with NoSQL databases, ensuring lightweight and responsive applications.
* Database Agnosticism: Supports a wide range of NoSQL databases, including key-value stores, document databases, and column-family stores. Offers flexibility to choose the most suitable database for specific use cases without major code changes.
* Rich Documentation and Ecosystem: Eclipse JNoSQL boasts a thriving community and comprehensive documentation, making it easy for developers to find support, tutorials, and examples. Integration with Quarkus allows tapping into the vibrant Quarkus ecosystem as well.

== Installation

To use this extension, add the `io.quarkiverse.jnosql:quarkus-jnosql` extension to your build file. For instance, with Maven, include the following dependency in your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Getting Started

Getting started with Quarkus JNoSQL is straightforward:

1. Add the Quarkus JNoSQL Extension to your project's dependencies. You can find the latest version on Maven Central.

   image::https://img.shields.io/maven-central/v/io.quarkiverse.jnosql/quarkus-jnosql-core?logo=apache-maven&style=flat-square[Version, link=https://search.maven.org/artifact/io.quarkiverse.jnosql/quarkus-jnosql-core]

2. Define your entities using JNoSQL annotations. For example:

[source,java]
----
import jakarta.nosql.Column;
import jakarta.nosql.Entity;
import jakarta.nosql.Id;

@Entity
public class TestEntity {

   @Id
   private String id;

   @Column
   private String testField;
}
----

== Key-Value Database Configuration

=== Configuration

Configure the JNoSql KeyValue Quarkus extension by specifying the name of the database that will be utilized within the Eclipse JNoSQL framework in your `application.properties`:

[source,properties]
----
jnosql.keyvalue.database=my-database-name
----

=== Usage

Inject the `KeyValueTemplate` into your class and use it to interact with the KeyValue database:

[source,java]
----
import jakarta.inject.Inject;
import org.jnosql.artemis.key.KeyValueTemplate;

@Inject
private KeyValueTemplate template;

public void insert(TestEntity entity) {
    template.insert(entity);
}
----

== Key-Value Database Specific Configuration

When configuring databases for use with Quarkus and Eclipse JNoSQL, it's important to note that instead of using the traditional Eclipse JNoSQL properties and configuration, Quarkus provides its properties and configuration for seamless integration. Below are sections detailing the configuration specifics for different NoSQL databases within the Quarkus environment.

TIP: Add sections for each specific database configuration, similar to those for ArangoDB, DynamoDB, Hazelcast, and Redis.

=== ArangoDB

Add the ArangoDB dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-keyvalue-arangodb</artifactId>
</dependency>
----

For specific configuration details, please refer to the link:https://github.com/eclipse/jnosql-databases#arangodb[ArangoDB JNoSQL driver].

=== DynamoDB

Add the DynamoDB dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-keyvalue-dynamodb</artifactId>
</dependency>
----

Please refer to the link:https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-dynamodb.html[DynamoDB Quarkiverse extension] for specific configuration details.

=== Hazelcast

Add the Hazelcast dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-keyvalue-hazelcast</artifactId>
</dependency>
----

Please refer to the link:https://github.com/hazelcast/quarkus-hazelcast-client[Quarkus Hazelcast extension] for specific configuration details.

=== Redis

Add the Redis dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-keyvalue-redis</artifactId>
</dependency>
----

For specific configuration details, please refer to the link:https://quarkus.io/guides/redis-reference[Redis Quarkus extension].

== Document Database Configuration

=== Configuration

Configure the JNoSql Document Quarkus extension by specifying the database's name in your `application.properties`:

[source,properties]
----
jnosql.document.database=my-database-name
----

=== Usage

Inject the `DocumentTemplate` into your class and use it to interact with the Document database:

[source,java]
----
import jakarta.inject.Inject;
import org.jnosql.artemis.document.DocumentTemplate;

@Inject
private DocumentTemplate template;

public void insert(TestDocumentEntity entity) {
    template.insert(entity);
}
----

== Document Database Specific Configuration

When configuring databases for use with Quarkus and Eclipse JNoSQL, it's important to note that instead of using the traditional Eclipse JNoSQL properties and configuration, Quarkus provides its properties and configuration for seamless integration. Below are sections detailing the configuration specifics for different NoSQL databases within the Quarkus environment.

TIP: Add sections for each specific database configuration, similar to those for ArangoDB, CouchDB, Elasticsearch, MongoDB, and Solr.

=== ArangoDB

Add the ArangoDB dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-document-arangodb</artifactId>
</dependency>
----

For specific configuration details, please refer to the link:https://github.com/eclipse/jnosql-databases#arangodb[ArangoDB JNoSQL driver].

=== CouchDB

Add the CouchDB dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-document-couchdb</artifactId>
</dependency>
----

For specific configuration details, please refer to the link:https://github.com/eclipse/jnosql-databases#couchdb[CouchDB JNoSQL driver].

=== Elasticsearch

Add the Elasticsearch dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-document-elasticsearch</artifactId>
</dependency>
----

For specific configuration details, please refer to the link:https://github.com/eclipse/jnosql-databases?tab=readme-ov-file#elasticsearch[ElasticSearch driver].

=== MongoDB

Add the MongoDB dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-document-mongodb</artifactId>
</dependency>
----

For specific configuration details, please refer to the link:https://quarkus.io/guides/mongodb#quarkus-mongodb-config-group-dev-services-build-time-config_configuration[MongoDB configuration].

=== Solr

Add the Solr dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-document-solr</artifactId>
</dependency>
----

For specific configuration details, please refer to the link:https://github.com/eclipse/jnosql-databases#solr[Solr JNoSQL driver].

== Column Database Configuration

=== Configuration

Configure the JNoSql Column Quarkus extension by specifying the database's name in your `application.properties`:

[source,properties]
----
jnosql.column.database=my-database-name
----

=== Usage

Inject the `ColumnTemplate` into your class and use it to interact with the Column database:

[source,java]
----
import jakarta.inject.Inject;
import org.jnosql.artemis.column.ColumnTemplate;

@Inject
private ColumnTemplate template;

public void insert(TestColumnEntity entity) {
    template.insert(entity);
}
----

== Column Database Specific Configuration

=== Cassandra

Add the Cassandra dependency to your project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jnosql</groupId>
    <artifactId>quarkus-jnosql-column-cassandra</artifactId>
</dependency>
----


Please refer to the link:https://quarkus.io/guides/cassandra[Cassandra Quarkus extension] for specific configuration details.

include::includes/quarkus-jnosql.adoc[leveloffset=+1, opts=optional]
